import React from 'react';
import {
  BookOpen,
  ShieldAlert,
  ShieldCheck,
  Cpu,
  Layers,
  BarChart3,
  GitFork,
  Target
} from 'lucide-react';

export const MethodologyView: React.FC = () => {
  return (
    <div className="space-y-8 pb-12 max-w-5xl">
      {/* Header Info */}
      <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-xs">
        <div className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-iceberg-50 text-iceberg-700 text-xs font-semibold mb-2">
          <BookOpen className="w-3.5 h-3.5" />
          <span>Scientific & Analytical Rigor Documentation</span>
        </div>
        <h3 className="text-xl font-bold text-slate-900 tracking-tight">
          MarketingIQ Mathematical & Econometric Methodology
        </h3>
        <p className="text-xs text-slate-500 mt-1">
          Detailed formulation of data preparation, K-Means clustering, Hill-equation response curves, constrained equimarginal optimization, and causal safety principles.
        </p>
      </div>

      {/* Mandatory Causal & Data Science Safety Notice (Requirement 24 & 30) */}
      <div className="p-6 rounded-2xl bg-amber-50/80 border border-amber-200 text-amber-950 space-y-2">
        <div className="flex items-center gap-2">
          <ShieldAlert className="w-5 h-5 text-amber-600 shrink-0" />
          <h4 className="text-sm font-bold uppercase tracking-wider text-amber-900">
            Fundamental Limitation & Data Science Safety Notice
          </h4>
        </div>
        <p className="text-xs text-amber-900 leading-relaxed font-medium">
          "Historical observational data cannot automatically establish causal relationships between marketing spend and revenue. Predictions and recommendations generated by MarketingIQ represent empirical observational estimates based on fitted response curves and historic covariance, not guaranteed counterfactual outcomes. Incremental changes should be deployed in randomized or staged geographical test splits."
        </p>
      </div>

      {/* Section 1: Data Preparation & Normalization */}
      <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-xs space-y-3">
        <div className="flex items-center gap-2.5 text-slate-900 font-bold text-base">
          <div className="w-7 h-7 rounded-lg bg-blue-50 text-blue-600 flex items-center justify-center text-xs">
            1
          </div>
          <span>Data Ingestion, Cleaning & Normalization</span>
        </div>
        <p className="text-xs text-slate-600 leading-relaxed">
          Marketing datasets frequently suffer from skewed distributions, currency symbol anomalies, and missing funnel stages. The ingestion pipeline:
        </p>
        <ul className="list-disc list-inside text-xs text-slate-600 space-y-1.5 pl-2">
          <li><strong>Sanitization:</strong> Strips Indian Rupee (<code className="bg-slate-100 px-1 py-0.5 rounded">₹</code>) and comma delimiters (<code className="bg-slate-100 px-1 py-0.5 rounded">1,00,000</code>), casting fields into IEEE-754 floating-point numbers.</li>
          <li><strong>Outlier & Missing Handling:</strong> Missing conversions default to conservative baseline attribution ratios derived from upstream lead volumes. Extreme outliers beyond 3 standard deviations are clipped to 99th percentile boundaries.</li>
          <li><strong>Standardization (Z-score):</strong> For distance-based clustering algorithms:
            <div className="my-2 p-2 bg-slate-50 font-mono text-center rounded border border-slate-200 text-[11px]">
              z = (x - μ) / σ
            </div>
          </li>
        </ul>
      </div>

      {/* Section 2: K-Means Customer Clustering */}
      <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-xs space-y-3">
        <div className="flex items-center gap-2.5 text-slate-900 font-bold text-base">
          <div className="w-7 h-7 rounded-lg bg-indigo-50 text-indigo-600 flex items-center justify-center text-xs">
            2
          </div>
          <span>K-Means Clustering & Dynamic Segment Synthesis</span>
        </div>
        <p className="text-xs text-slate-600 leading-relaxed">
          Customer segments are identified via multi-dimensional unsupervised learning rather than arbitrary rule-sets.
        </p>
        <div className="p-3 bg-slate-50 rounded-xl border border-slate-200 font-mono text-xs text-center text-slate-800">
          J = Σ Σ || x_i^(j) - c_j ||²
        </div>
        <p className="text-xs text-slate-600 leading-relaxed">
          The feature vector includes: <em>[Revenue, 3-Year Estimated CLV, Average Deal Value, Lead Conversion %, Interaction Volume, Spend]</em>. Initialization uses the <strong>K-Means++</strong> seeding technique to maximize initial cluster separation. Cluster labels (e.g. <em>Enterprise High-Value, Strategic Growth</em>) are synthesized dynamically by evaluating centroid feature ratios against global baseline averages.
        </p>
      </div>

      {/* Section 3: S-Curve / Hill Equation Marginal Returns */}
      <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-xs space-y-3">
        <div className="flex items-center gap-2.5 text-slate-900 font-bold text-base">
          <div className="w-7 h-7 rounded-lg bg-emerald-50 text-emerald-600 flex items-center justify-center text-xs">
            3
          </div>
          <span>Diminishing Returns & Marginal ROI Modeling (Hill Equation)</span>
        </div>
        <p className="text-xs text-slate-600 leading-relaxed">
          Linear marketing models dangerously assume that doubling spend will double revenue indefinitely. In reality, marketing channels exhibit S-shaped saturation curves governed by the modified Hill response function:
        </p>
        <div className="p-3 bg-slate-50 rounded-xl border border-slate-200 font-mono text-xs text-center text-slate-800">
          R(s) = R_max · [ s^γ / (K^γ + s^γ) ]
        </div>
        <p className="text-xs text-slate-600 leading-relaxed">
          Where:
        </p>
        <ul className="list-disc list-inside text-xs text-slate-600 space-y-1 pl-2">
          <li><strong>R_max:</strong> Channel revenue ceiling capacity under maximum saturation.</li>
          <li><strong>K:</strong> Half-saturation spend (the expenditure required to reach 50% of maximum revenue).</li>
          <li><strong>γ:</strong> Shape elasticity parameter (empirically set to 1.35 for B2B enterprise sales).</li>
        </ul>
        <p className="text-xs text-slate-600 leading-relaxed">
          The <strong>Marginal Return (dR/ds)</strong> is the first derivative with respect to spend:
        </p>
        <div className="p-3 bg-slate-50 rounded-xl border border-slate-200 font-mono text-xs text-center text-slate-800">
          dR/ds = [ R_max · γ · K^γ · s^(γ - 1) ] / (K^γ + s^γ)²
        </div>
        <p className="text-xs text-slate-600 leading-relaxed">
          When dR/ds falls below 1.0, additional rupees generate less than ₹1 of incremental revenue (loss-making saturation).
        </p>
      </div>

      {/* Section 4: Constrained Optimization Engine */}
      <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-xs space-y-3">
        <div className="flex items-center gap-2.5 text-slate-900 font-bold text-base">
          <div className="w-7 h-7 rounded-lg bg-amber-50 text-amber-600 flex items-center justify-center text-xs">
            4
          </div>
          <span>Constrained Budget Optimization & Equimarginal Allocation</span>
        </div>
        <p className="text-xs text-slate-600 leading-relaxed">
          The budget optimizer solves the constrained resource allocation problem:
        </p>
        <div className="p-3 bg-slate-50 rounded-xl border border-slate-200 font-mono text-xs text-slate-800 space-y-1">
          <div>Maximize: Σ R_i(s_i)</div>
          <div>Subject to: Σ s_i = Total_Budget</div>
          <div>and: L_i ≤ s_i ≤ U_i (Channel Bounds & Strategic Floor Locks)</div>
        </div>
        <p className="text-xs text-slate-600 leading-relaxed">
          Under the <strong>Equimarginal Principle</strong>, portfolio return is maximized when the marginal revenue per rupee is equal across all unconstrained channels. The solver applies discrete projected increments to continuously reallocate capital from low-marginal to high-marginal channels until optimality is attained.
        </p>
      </div>

      {/* Section 5: Campaign Effectiveness Score (CES) */}
      <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-xs space-y-3">
        <div className="flex items-center gap-2.5 text-slate-900 font-bold text-base">
          <div className="w-7 h-7 rounded-lg bg-violet-50 text-violet-600 flex items-center justify-center text-xs">
            5
          </div>
          <span>Campaign Effectiveness Score (CES: 0–100) Formulation</span>
        </div>
        <p className="text-xs text-slate-600 leading-relaxed">
          CES normalizes 5 distinct operational metrics into a single balanced scorecard:
        </p>
        <div className="p-3 bg-slate-50 rounded-xl border border-slate-200 font-mono text-xs text-center text-slate-800">
          CES = w_1 · ROI_norm + w_2 · ConvRate_norm + w_3 · RevShare_norm + w_4 · LeadQuality_norm + w_5 · (100 - CAC_norm)
        </div>
        <p className="text-xs text-slate-600 leading-relaxed">
          Default baseline weights: 25% ROI, 20% Conversion Rate, 25% Revenue Contribution, 20% Lead Quality (SQL/Lead ratio), and 10% CAC Efficiency. Users can customize weights directly in Campaign Analytics.
        </p>
      </div>
    </div>
  );
};
